# Generated by Django 5.1.7 on 2025-03-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=100)),
                ('interests', models.TextField(help_text='Comma-separated interests like food, history, adventure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
