# Generated by Django 5.1.7 on 2025-04-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
